### ISSUE TITLE
List of Ruby/RoR company

### ISSUE THREAD

**Issue by vivrass** [montrealrb/Montreal.rb#7] opened 2013-07-30 13:14 UTC
We need a list + a map of all the company using Ruby and RoR in Montreal/Quebec with their contact information.

If would be nice to know when the sponsored an activity.

**Comment by sophiedeziel** [comment] 2015-11-04 03:15
duplicate of #18 (18 is more detailed)

**Closed by sophiedeziel** 2015-11-04 03:15 UTC
